on:
  workflow_dispatch:
  push:
    branches:
      - main

name: fox32 tools Unstable - Linux

jobs:
  tools-unstable-linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: nix build -L .#gfx2inc

      - name: Patch
        run: nix run nixpkgs#patchelf -- result/bin/gfx2inc --set-interpreter /lib64/ld-linux-x86-64.so.2 --output gfx2inc/gfx2inc

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gfx2inc
          path: gfx2inc/gfx2inc
